### ISSUE TITLE
Flip01-notebook

### ISSUE THREAD

**Issue by Jiang29** [tulip-lab/flip01#1]
Matrix Analysis:

In F1A-02 Gram-schmidtAlgorithmn，the first block has code:

```
Q = numpy.matrix( numpy.empty( shape=M.shape ) )

R = numpy.matrix( numpy.empty( shape=M.shape ) )
```

In Python3, it would generate a matrix the same as M. But in real we want to generate zeros matrix with the same shape as M. So, we can call np.zeros like the following:

```
Q = numpy.matrix( numpy.zeros( shape=M.shape ) )

R = numpy.matrix( numpy.zeros( shape=M.shape ) )
```

ML:

In F1C-01-MLGridSearch, the 11th code blocks, when generating a GridSearchCV instance, it need to add a parameters **_return_train_score=True_** to return the important data **mean_train_AUC**, which is used in the next block.

**Comment by dmy666** [comment]
Have changed.
